### ISSUE TITLE
Integrating Flood Maps with Existing Map

### ISSUE THREAD

**Issue by aswinmohanme** [aswinmohanme/kerala-flood-map#15]
This https://www.microid.in/keralaflood/ maps out all the roads that are unsafe to travel along. It would be helpful if we could in any way integrate it to the existing map

**Comment by aswinmohanme** [comment]
moved from https://github.com/IEEEKeralaSection/rescuekerala/issues/243

**Comment by bodhish** [comment]
@aswinmohanme how about a button on top to find the `flooding near you` that points users to the flood map with their location

**Comment by answerquest** [comment]
Yes, the button can just take the map's current zoom and location and supply them in URL params for the floodmap.  
Example: https://www.microid.in/keralaflood/#14/10.30143/76.32793
syntax is: `https://www.microid.in/keralaflood/#{zoom}/{latitude}/{longitude}`

@aswinmohanme I seriously feel vanilla leaflet would be easier to code than react-leaflet.

**Comment by answerquest** [comment]
that map is a mapbox vector map and has loading/performance issues of its own, so it might be better not to bring it directly into this map. Let people open the exact same location in another browser tab. `target="_blank"`
