### ISSUE TITLE
Show Flood Prediction Data on Map

### ISSUE THREAD

**Issue by aswinmohanme** [aswinmohanme/kerala-flood-map#23]

**Comment by Demisane** [comment]
Uploading a prediction rendered raster. This data entails watershed data in intersection with the rivers features obtained from osm. Sample image of floodzones currently being uploaded. https://i.imgur.com/uB7BQCc.png

**Comment by Demisane** [comment]
Just uploaded the floodzone around rivers tiff file to mapbox with id 'demisane.dffgs0yv' The darker colouration shows lower watershed where water will flow into.

**Comment by geohacker** [comment]
Looking at this now.
![image](https://user-images.githubusercontent.com/371666/44262158-a6caa700-a237-11e8-8c51-7ec4b934ff3f.png)

Will make a PR

**Comment by bodhish** [comment]
Nice work @geohacker

**Comment by aswinmohanme** [comment]
When zooming in the colors mask the names of the places below them

**Comment by aswinmohanme** [comment]
Reducing opacity might help, I have set it at 0.4
![screenshot from 2018-08-17 16-35-12](https://user-images.githubusercontent.com/20600674/44263546-0081a000-a23d-11e8-951f-c594a089e75c.png)

**Comment by Demisane** [comment]
Is it possible to keep two layers? One opaque and the other transparent. The colour variation should give people an idea of where to head out from and in what direction

**Comment by aswinmohanme** [comment]
What is this prediction based on ?

**Comment by Demisane** [comment]
watersheds, built those from slopes generated from digital elevation models obtained from ASTER. I have added a rescue request heatmap for Kerala (demisane.24pppbbz). Working on making a detailed one at the district level

**Comment by Demisane** [comment]
Heatmaps generated from data from 17th August 2018, collected by 1400UTC

Overall: demisane.24pppbbz
5k influence heatmap (less defined at low resolution): demisane.7e9rfjt5
2.5kinfluence heatmap (better defined at low resolution): demisane.d20zn6h1
