### ISSUE TITLE
Zoom problem in the map(only in track pads ?)

### ISSUE THREAD

**Issue by sravan-s** [aswinmohanme/kerala-flood-map#30]
Does anyone else's map go zoom multiple levels like this on single scroll?

![map](https://user-images.githubusercontent.com/11382805/44280002-677b7500-a28e-11e8-8a58-77f68ae5ea8e.gif)

I am on a macbook, if that is the problem, feel free to close

**Comment by bodhish** [comment]
I am not facing any issues, Can you note down the process of replicating this.
Closing this for now

**Comment by sravan-s** [comment]
STR: Just try to zoom in using track-pad
