### ISSUE TITLE
Add location on pop-ups 

### ISSUE THREAD

**Issue by bodhish** [aswinmohanme/kerala-flood-map#4]
This could help others navigate to the location for rescues.

**Comment by aswinmohanme** [comment]
Like a google maps link ?

**Comment by bodhish** [comment]
@aswinmohanme Yep, This could help people. 
if you want i can work on it

**Comment by aswinmohanme** [comment]
@bodhish go ahead

**Comment by aswinmohanme** [comment]
Fixed by #11
