### ISSUE TITLE
PropTypes for marker

### ISSUE THREAD

**Issue by appunnicer13** [aswinmohanme/kerala-flood-map#5]
MainPage.propTypes = {
  position: PropTypes.arrayOf(PropTypes.number.isRequired),
  zoomLevel: PropTypes.number,
  markers: PropTypes.arrayOf(PropTypes.shape({
    map: PropTypes.shape({
      latlng: PropTypes.string.isRequired,
      needrescue: PropTypes.bool,
      requestee: PropTypes.string.isRequired,
      location: PropTypes.string.isRequired,
      requestee_phone: PropTypes.string.isRequired,
      detailfood: PropTypes.string,
      detailcloth: PropTypes.string,
      detailwater: PropTypes.string,
      detailtoilet: PropTypes.string,
      detailmed: PropTypes.string,
      needothers: PropTypes.string,
      detailkit_util: PropTypes.string,
      needkit_util: PropTypes.string,
    })
  }))
}

**Comment by aswinmohanme** [comment]
Create a PR with the code

**Comment by appunnicer13** [comment]
#8 Resolution

**Comment by aswinmohanme** [comment]
Fixed
