### ISSUE TITLE
Lazy Load Data Points

### ISSUE THREAD

**Issue by aswinmohanme** [aswinmohanme/kerala-flood-map#7]
Currently we get the entire data dump from the sever. This is expected to grow and considerably slows down the site.

We should load the data of the immediate surroundings first

**Comment by appunnicer13** [comment]
Any implementation to filter the whole data will result in use of more CPU and RAM from USERs device which will considerably slow down. Its always a better idea to get the data dynamically by passing latitude longitude and  letting server take the load for it. But If we can get district wise data may be this will be possible, but as more people mark it here more the load is going to be

**Comment by appunnicer13** [comment]
https://www.npmjs.com/package/geolib

**Comment by appunnicer13** [comment]
What is the initial window ?

**Comment by aswinmohanme** [comment]
I don't understand

**Comment by appunnicer13** [comment]
Currently I don't load points unless they click on near me

**Comment by appunnicer13** [comment]
What should be the initial window , if I shouldn't be loading points

**Comment by aswinmohanme** [comment]
We should zoom near to the location of the user and load those points. The zoom level should not be as close as the one which shows up when we click on the locate near me

**Comment by RevathiKannanGithub** [comment]
More than district, do we have zones/divisions of districts in kerala?

**Comment by appunnicer13** [comment]
Yeah that is happening automatically, I am showing points near 10km radius

**Comment by appunnicer13** [comment]
But is initial window is empty now. I will give a pull request you let me know

**Comment by appunnicer13** [comment]
Create a branch called lazy loading 
I will do pull request there

**Comment by appunnicer13** [comment]
intial commit on lazy loading #12

**Comment by appunnicer13** [comment]
distance selection  #17
